import { createStorageContext } from './storage-context.js';

const {
  RUN_FILTER_STORAGE_KEY,
  RUN_FILTER_AUTO,
  RUN_FILTER_ALL,
  RUN_FILTER_UNKNOWN,
  safeLocalStorageGet,
  safeLocalStorageSet,
  THEME_STORAGE_KEY,
  DISPATCH_CWD_STORAGE_KEY,
  HIDDEN_RUNS_STORAGE_KEY,
  WORKSPACE_ROOT_STORAGE_KEY_PREFIX,
  WORKSPACE_EXPLORER_SPLIT_WIDTH_KEY_PREFIX,
  WORKSPACE_EXPLORER_AUTO_OPEN_HISTORY_KEY,
  FLOATING_ISLAND_COLLAPSED_STORAGE_KEY,
  buildWorkspaceRootStorageKey,
  buildWorkspaceExplorerSplitWidthStorageKey,
} = createStorageContext('deepseek_cli.ui');

export {
  RUN_FILTER_STORAGE_KEY,
  RUN_FILTER_AUTO,
  RUN_FILTER_ALL,
  RUN_FILTER_UNKNOWN,
  safeLocalStorageGet,
  safeLocalStorageSet,
  THEME_STORAGE_KEY,
  DISPATCH_CWD_STORAGE_KEY,
  HIDDEN_RUNS_STORAGE_KEY,
  WORKSPACE_ROOT_STORAGE_KEY_PREFIX,
  WORKSPACE_EXPLORER_SPLIT_WIDTH_KEY_PREFIX,
  WORKSPACE_EXPLORER_AUTO_OPEN_HISTORY_KEY,
  FLOATING_ISLAND_COLLAPSED_STORAGE_KEY,
  buildWorkspaceRootStorageKey,
  buildWorkspaceExplorerSplitWidthStorageKey,
};
