import {
  RUN_FILTER_AUTO,
  RUN_FILTER_ALL,
  RUN_FILTER_UNKNOWN,
  buildScopedStorageKey,
  createStorageKeys,
  safeLocalStorageGet,
  safeLocalStorageSet,
} from './storage-helpers.js';

const STORAGE_KEYS = createStorageKeys('deepseek_cli.ui');

export const RUN_FILTER_STORAGE_KEY = STORAGE_KEYS.RUN_FILTER_STORAGE_KEY;
export { RUN_FILTER_AUTO, RUN_FILTER_ALL, RUN_FILTER_UNKNOWN, safeLocalStorageGet, safeLocalStorageSet };
export const THEME_STORAGE_KEY = STORAGE_KEYS.THEME_STORAGE_KEY;
export const DISPATCH_CWD_STORAGE_KEY = STORAGE_KEYS.DISPATCH_CWD_STORAGE_KEY;
export const HIDDEN_RUNS_STORAGE_KEY = STORAGE_KEYS.HIDDEN_RUNS_STORAGE_KEY;
export const WORKSPACE_ROOT_STORAGE_KEY_PREFIX = STORAGE_KEYS.WORKSPACE_ROOT_STORAGE_KEY_PREFIX;
export const WORKSPACE_EXPLORER_SPLIT_WIDTH_KEY_PREFIX = STORAGE_KEYS.WORKSPACE_EXPLORER_SPLIT_WIDTH_KEY_PREFIX;
export const WORKSPACE_EXPLORER_AUTO_OPEN_HISTORY_KEY = STORAGE_KEYS.WORKSPACE_EXPLORER_AUTO_OPEN_HISTORY_KEY;
export const FLOATING_ISLAND_COLLAPSED_STORAGE_KEY = STORAGE_KEYS.FLOATING_ISLAND_COLLAPSED_STORAGE_KEY;

export function buildWorkspaceRootStorageKey(runScope) {
  return buildScopedStorageKey(WORKSPACE_ROOT_STORAGE_KEY_PREFIX, runScope, RUN_FILTER_ALL);
}

export function buildWorkspaceExplorerSplitWidthStorageKey(runScope) {
  return buildScopedStorageKey(WORKSPACE_EXPLORER_SPLIT_WIDTH_KEY_PREFIX, runScope, RUN_FILTER_ALL);
}
